### ISSUE TITLE
Add Visibiity to Discord Origin

### ISSUE THREAD

**Issue by gaf3** [unum-origins/discord#10]
The visibility system has three distinct levels:

Private Information:
Strictly between user and bot
Examples: Direct messages on Slack or Discord
This classification system helps manage information sharing across different platforms while maintaining appropriate levels of confidentiality.

Public Information:
Visible to others besides user and bot
Examples: Public Facebook posts, regular Discord channel posts

**ADC**
- Witness settings, what is written to Facts
  - write: 
    - private - between bot and user only
    - public - completely open in the domain
- Herald settings, what is read from Facts
  - read: 
    - private - between bot and user only
    - public - completely open in the domain
- Herald settings, what is written to Acts
  - write: 
    - private - between bot and user only
    - public - completely open in the domain
- Witness settings, what is read from Facts
  - write: 
    - private - between bot and user only
    - public - completely open in the domain

**Comment by gaf3** [comment]
Tie into ntofication

**Comment by gaf3** [comment]
``` 
- name: quepasa
  description: Manage me (bot) checking in on you
  usages:
  - name: start_every
    description: I will check on you every {every}
    args:
    - name: every
      format: duration
      description: Check in every {every}
  - name: start_from_to
    description: I will check on you from every {from} to every {to}
    args:
    - name: from
      description: Check in earliest every {from}
      format: duration
    - name: to
      description: Check in latest every {to}
      format: duration
  - name: stop
    description: I will not check on you
    args:
    - name: stop
      valids:
      - stop
```

becomes:

``` 
- name: quepasa
  description: Manage me (bot) checking in on you
  usages:
  - name: start_every
    description: I will check on you every {every}
    args:
    - name: every
      format: duration
      description: Check in every {every}
  - name: start_from_to
    description: I will check on you from every {from} to every {to}
    args:
    - name: from
      description: Check in earliest every {from}
      format: duration
    - name: to
      description: Check in latest every {to}
      format: duration
  - name: stop
    description: I will not check on you
    args:
    - name: stop
      valids:
      - stop
```

No join to overall commands
