### ISSUE TITLE
Upgrade Help System

### ISSUE THREAD

**Issue by gaf3** [unum-origins/discord#8]
# Discord

## From:
```yaml
description: The Discord Origin, which interfaces with this Unum.
channel: unifist-unum
commands:
- name: join
  description: Join this Unum and Discord Origin and Leader App. It'll track everything you say in this Discord Guild to this Unum's Ledger.
```

## To: 

```yaml
description: The Discord Origin, which interfaces with this Unum.
channel: unifist-unum
commands:
- name: join
  description: Join this Unum and Discord Origin and Leader App. It'll track everything you say in this Discord Guild to this Unum's Ledger.
  requires: none # default is herald
```

# Ledger:

## From:
```yaml
channel: unum-ledger
description: Base App of an Unum, records and coordinates all
commands:
- name: apps
  description: List all the installed Apps in this Unum.
- name: origins
  description: List all the installed Apps in this Unum.
- name: who
  description: Shows your current name in the Unum
- name: who {who}
  description: Changes your current name to {who} in the Unum
  ```

## To: 

```yaml
channel: unum-ledger
description: Base App of an Unum, records and coordinates all
commands:
- name: apps
  description: List all the installed Apps in this Unum.
- name: origins
  description: List all the installed Apps in this Unum.
- name: who
  description: Manages your Name in the Unum
  usage:
  - pattern: who 
    description: Shows your current name in the Unum
  - pattern: who {name}
    description: Changes your current name to {who} in the Unum
    args:
    - name: name
      description: The full name with spaces you want 
      format: remainder
```

# TehFeelz:

## From:
```yaml
channel: unum-tehfeelz
description: Tracks yours and others feelings and the relationships between. All when's are in 3d2h1m = 3 days 2 hour 1 min format
commands:
- name: join
  description: Join the TehFeelz App
- name: state {state}
  description: Record whether you're current state, values are good or bad
- name: state {when}
  description: List your states from {when} ago to now
- name: state {when_min} {when_max}
  description: List your states from {when_min} to {when_max}
- name: mood {emoji}
  description: Record your current mood in terns of an emoji
- name: mood {when}
  description: List your moods from {when}
- name: mood {when_min} {when_max}
  description: List your moods from {when_min} to {when_max}
- name: diary {words}
  description: Record your current mood in terns of words
- name: diary {when}
  description: List your diaries from {when}
- name: diary {when_min} {when_max}
  description: List your diaries from {when_min} to {when_max}
```

## To: 

```yaml
channel: unum-tehfeelz
description: Tracks yours and others feelings and the relationships between. All when's are in 3d2h1m = 3 days 2 hour 1 min format
commands:
- name: join
  description: Join the TehFeelz App
  requires: unum
- name: state
  description: Record or list your state of mind, good or bad
  usage:
  - pattern: state {state}
    description: Record your current state as {state}
    args:
    - name: state
      options:
      - good
      - bad
  - pattern: state {since}
    description: List your states from {since} ago to now
    args:
    - name: since
      description: How far back to list 
      format: duration
  - pattern: state {from} {to}
     description: List your states from {from} to {to}
     args:
    - name: from
      description: How far back to start listing 
      format: duration
    - name: to
      description: How far back to stop listing  
      format: duration
- name: mood
  description: Record or list your mood with an emoji
  usage:
  - pattern: mood {mood}
    description: Record your current mood
    args:
    - name: mood
      format: emoji
  - pattern: mood {since}
    description: List your moods from {since} ago to now
    args:
    - name: since
      description: How far back to list 
      format: duration
  - pattern: mood {from} {to}
     description: List your moods from {from} to {to}
    args:
    - name: from
      description: How far back to start listing 
      format: duration
    - name: to
      description: How far back to stop listing  
      format: duration
- name: diary
  description: Record or list your thoughts
  usage:
  - pattern: diary {thoughts}
    description: Record your current thoughts
    args:
    - name: thoughts
      format: remainder
  - pattern: diary {since}
    description: List your thoughts from {since} ago to now
    args:
    - name: since
      description: How far back to list 
      format: duration
  - pattern: diary {from} {to}
     description: List your thoughts from {from} to {to}
    args:
    - name: from
      description: How far back to start listing 
      format: duration
    - name: to
      description: How far back to stop listing  
      format: duration
```
